#!/usr/bin/env python3
"""gen_tile_weights.py — Generate per-tile Verilog with baked-in weights

Given a weight matrix (from a trained model), generates one .v file
per tile with the weights as synthesis-time parameters.

The FPGA bitstream IS the neural network. Weights are gates.

Usage:
  python3 gen_tile_weights.py model_weights.json

Input format (JSON):
  {"layers": [
    {"weights": [[w00,w01,...],[w10,w11,...],...]},
    {"weights": [[...],...]},
    ...
  ]}

Output: tile_layer_N.v per layer, with weight parameters filled in.
Synthesise each with: yosys + nextpnr-ice40 → bitstream per tile.
"""

import json, sys, os

TEMPLATE = '''// Auto-generated tile for layer {layer_idx}
// Weights baked into LUT configuration — the bitstream IS the model
// Generated by gen_tile_weights.py

module tile_layer_{layer_idx} (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        valid_in,
    input  wire [7:0]  x_in [0:7],
    output wire        valid_out,
    output wire [15:0] y_out [0:7],
    input  wire        relu_en
);

    tile_matmul_8x8 #(
{params}
    ) matmul (
        .clk       (clk),
        .rst_n     (rst_n),
        .valid_in  (valid_in),
        .x_in      (x_in),
        .valid_out (valid_out),
        .y_out     (y_out),
        .relu_en   (relu_en)
    );

endmodule
'''

def clamp_int8(v):
    return max(-128, min(127, int(round(v))))

def gen_layer(layer_idx, weights):
    """Generate Verilog for one 8×8 tile with baked weights."""
    params = []
    for i in range(8):
        for j in range(8):
            w = clamp_int8(weights[i][j]) if i < len(weights) and j < len(weights[i]) else 0
            # Verilog signed 8-bit literal
            if w < 0:
                params.append(f"        .W{i}{j}(-8'sd{abs(w)})")
            else:
                params.append(f"        .W{i}{j}(8'sd{w})")

    return TEMPLATE.format(
        layer_idx=layer_idx,
        params=",\n".join(params)
    )

def main():
    if len(sys.argv) < 2:
        # Demo: generate a sample 3-layer network
        print("No model file specified. Generating demo 3-layer network.")
        demo_layers = [
            {"weights": [[10,0,0,0,0,0,0,0],
                         [0,20,0,0,0,0,0,0],
                         [0,0,-5,0,0,0,0,0],
                         [0,0,0,1,0,0,0,0],
                         [0,0,0,0,1,0,0,0],
                         [0,0,0,0,0,1,0,0],
                         [0,0,0,0,0,0,1,0],
                         [0,0,0,0,0,0,0,1]]},
            {"weights": [[1,1,1,1,0,0,0,0],
                         [0,0,0,0,1,1,1,1],
                         [1,0,1,0,1,0,1,0],
                         [0,1,0,1,0,1,0,1],
                         [1,1,0,0,1,1,0,0],
                         [0,0,1,1,0,0,1,1],
                         [1,0,0,1,1,0,0,1],
                         [0,1,1,0,0,1,1,0]]},
            {"weights": [[1,1,1,1,1,1,1,1],
                         [-1,1,-1,1,-1,1,-1,1],
                         [1,-1,1,-1,1,-1,1,-1],
                         [1,1,-1,-1,1,1,-1,-1],
                         [-1,-1,1,1,-1,-1,1,1],
                         [1,1,1,1,-1,-1,-1,-1],
                         [-1,-1,-1,-1,1,1,1,1],
                         [1,-1,-1,1,-1,1,1,-1]]}
        ]
        model = {"layers": demo_layers}
    else:
        with open(sys.argv[1]) as f:
            model = json.load(f)

    outdir = os.path.join(os.path.dirname(__file__), "rtl", "matmul", "tiles")
    os.makedirs(outdir, exist_ok=True)

    for i, layer in enumerate(model["layers"]):
        code = gen_layer(i, layer["weights"])
        path = os.path.join(outdir, f"tile_layer_{i}.v")
        with open(path, "w") as f:
            f.write(code)
        print(f"[OK] {path}")

    # Generate top-level chain
    n = len(model["layers"])
    chain_code = gen_chain_top(n)
    path = os.path.join(outdir, f"chain_top.v")
    with open(path, "w") as f:
        f.write(chain_code)
    print(f"[OK] {path}")

    print(f"\n{'='*60}")
    print(f" Generated {n}-layer tile chain")
    print(f" {n}× iCE40HX8K = £{n*3.80:.2f}")
    print(f" Pipeline: {n} clocks latency, 1 inference/clock")
    print(f" At 133MHz: 133M inferences/sec")
    print(f" Weights ARE the bitstream. The FPGA IS the model.")
    print(f"{'='*60}")

def gen_chain_top(n_layers):
    insts = []
    wires = []

    for i in range(n_layers):
        prev = f"x_in" if i == 0 else f"inter_{i}"
        nxt = f"y_out" if i == n_layers - 1 else f"inter_{i+1}"
        v_prev = "valid_in" if i == 0 else f"v_{i}"
        v_nxt = "valid_out" if i == n_layers - 1 else f"v_{i+1}"

        if i < n_layers - 1:
            wires.append(f"    wire [15:0] inter_{i+1} [0:7];")
            wires.append(f"    wire v_{i+1};")

        # Requantize wires (16→8 bit) for non-first layers
        if i > 0:
            wires.append(f"    wire [7:0] rq_{i} [0:7];")
            for v in range(8):
                wires.append(f"    assign rq_{i}[{v}] = ($signed(inter_{i}[{v}]) > 127) ? 8'd127 : ($signed(inter_{i}[{v}]) < -128) ? -8'd128 : inter_{i}[{v}][7:0];")

        x_conn = "x_in" if i == 0 else f"rq_{i}"
        relu = "1'b1" if i < n_layers - 1 else "1'b0"

        insts.append(f"""    tile_layer_{i} layer_{i} (
        .clk(clk), .rst_n(rst_n),
        .valid_in({v_prev}), .x_in({x_conn}),
        .valid_out({v_nxt}), .y_out({nxt}),
        .relu_en({relu})
    );""")

    return f"""// Auto-generated chain top for {n_layers}-layer network
module chain_top (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        valid_in,
    input  wire [7:0]  x_in [0:7],
    output wire        valid_out,
    output wire [15:0] y_out [0:7]
);

{chr(10).join(wires)}

{chr(10).join(insts)}

endmodule
"""

if __name__ == "__main__":
    main()
